# Migrate a Neutron deployment using ML2/OVS to OVN.
#
# See hosts-sample for expected contents of the ansible inventory.

---
- hosts: compute
  remote_user: root

  tasks:
  - name: Ensure OVN packages are installed on compute nodes.
    yum:
      name: openvswitch-ovn-host
      state: present

  # TODO to make ansible-lint happy, all of these commands should be conditionally run
  # only if the config value needs to be changed.
  - name: Configure ovn-encap-type.
    command: "ovn-vsctl set open . external_ids:ovn-encap-type=geneve"

  - name: Configure ovn-encap-ip.
    command: "ovn-vsctl set open . external_ids:ovn-encap-ip={{ ovn_encap_ip }}"

  - name: Configure ovn-remote.
    command: "ovn-vsctl set open . external_ids:ovn-remote=tcp:{{ ovn_db_ip }}:6642"
    # TODO We could discover the appropriate value for ovn-bridge-mappings based on
    # the openvswitch agent configuration instead of requiring it to be configured
    # in the inventory.

  - name: Configure ovn-bridge-mappings.
    command: "ovn-vsctl set open . external_ids:ovn-bridge-mappings={{ ovn_bridge_mappings }}"

- hosts: controller
  remote_user: root

  tasks:
  - name: Ensure OVN packages are installed on the central OVN host.
    when: ovn_central
    yum:
      name: openvswitch-ovn-central
      state: present

  # TODO Integrate HA support for the OVN control services.
  - name: Start ovn-northd and the OVN databases.
    when: ovn_central
    systemd:
      name: ovn-northd
      state: started

  - name: Enable remote access to the northbound database.
    command: "ovn-nbctl set-connection ptcp:6641:{{ ovn_db_ip }}"
    when: ovn_central

  - name: Enable remote access to the southbound database.
    command: "ovn-sbctl set-connection ptcp:6642:{{ ovn_db_ip }}"
    when: ovn_central

  - name: Ensure the Neutron ML2 plugin is installed on neutron-api hosts.
    yum:
      name: python-networking-ovn
      state: present

  - name: Update /etc/neutron/neutron.conf service_plugins.
    ini_file:
      path: /etc/neutron/neutron.conf
      section: DEFAULT
      option: service_plugins
      value: qos,networking_ovn.l3.l3_ovn.OVNL3RouterPlugin

  - name: Update /etc/neutron/neutron.conf qos notification_drivers.
    ini_file:
      path: /etc/neutron/neutron.conf
      section: DEFAULT
      option: notification_drivers
      value: ovn-qos

  - name: Configure to use OVN ML2 mechanism driver.
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ml2
      option: mechanism_drivers
      value: ovn

  - name: Configure ML2 type drivers.
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ml2
      option: type_drivers
      value: geneve,vxlan,vlan,flat

  - name: Configure ML2 type drivers.
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ml2
      option: extension_drivers
      value: qos,port_security

  - name: Configure ML2 Geneve type driver vni_ranges.
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ml2_type_geneve
      option: vni_ranges
      value: 1:65536

  - name: Configure ML2 Geneve type driver max_header_size.
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ml2_type_geneve
      option: max_header_size
      value: 38

  - name: Configure ML2 OVN mech driver ovn_nb_connection.
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ovn
      option: ovn_nb_connection
      value: "tcp:{{ ovn_db_ip }}:6641"

  - name: Configure ML2 OVN mech driver ovn_sb_connection.
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ovn
      option: ovn_sb_connection
      value: "tcp:{{ ovn_db_ip }}:6642"

  - name: Configure ML2 OVN mech driver ovsdb_connection_timeout.
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ovn
      option: ovsdb_connection_timeout
      value: 180

  - name: Configure ML2 OVN mech driver neutron_sync_mode.
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ovn
      option: neutron_sync_mode
      value: repair

  - name: Configure ML2 OVN mech driver ovn_l3_mode.
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ovn
      option: ovn_l3_mode
      value: true

  - name: Configure ML2 OVN mech driver vif_type.
    ini_file:
      path: /etc/neutron/plugins/ml2/ml2_conf.ini
      section: ovn
      option: vif_type
      value: ovs

  - name: Note that API downtime begins now.
    debug:
      msg: NEUTRON API DOWNTIME STARTING NOW FOR THIS HOST

  - name: Shut down neutron-server so that we can begin data sync to OVN.
    systemd:
      name: neutron-server
      state: stopped

- hosts: controller
  remote_user: root

  tasks:
  - name: Sync Neutron state to OVN.
    when: ovn_central
    command: neutron-ovn-db-sync-util
    # TODO What arguments are needed to the sync-util?

- hosts: overcloud
  remote_user: root

  tasks:
  - name: Note that data plane imact starts now.
    debug:
      msg: DATA PLANE IMPACT BEGINS NOW.

  - name: Stop metadata agent if needed.
    systemd:
      name: neutron-metadata-agent
      state: stopped

  - name: Stop DHCP agent if needed.
    systemd:
      name: neutron-dhcp-agent
      state: stopped

  - name: Stop L3 agent if needed.
    systemd:
      name: neutron-l3-agent
      state: stopped

  - name: Stop openvswitch agent if needed.
    systemd:
      name: neutron-openvswitch-agent
      state: stopped

- hosts: compute
  remote_user: root

  tasks:
  - name: Note that data plane is being restored.
    debug:
      msg: DATA PLANE IS NOW BEING RESTORED.

  - name: Reset OpenFlow protocol version before ovn-controller takes over.
    with_items: [ br-int, br-ex, br-tun ]
    command: "ovs-vsctl set Bridge {{ item }} protocols=[]"
    ignore_errors: True

  - name: Start ovn-controller.
    systemd:
      name: ovn-controller
      state: started

- hosts: controller
  remote_user: root

  tasks:
  - name: Note that the Neutron API is coming back online.
    debug:
      msg: THE NEUTRON API IS NOW BEING RESTORED.

  - name: Start neutron-server.
    systemd:
      name: neutron-server
      state: started

# TODO In our grenade script we had to restart rabbitmq.  Is that needed?
